# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [1]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [2]:
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [3]:
arr_1d = np.arange(10)
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [4]:
arr_bool = np.full((3, 3), True, dtype=bool)
print(arr_bool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [5]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)

[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [7]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [9]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
new_arr = np.where(arr % 2 == 1, -1, arr)
print(new_arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [11]:
# Input — do not modify
arr = np.arange(10)

In [12]:
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [13]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [14]:
arr_vstacked = np.vstack((a, b))
print(arr_vstacked)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [15]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [16]:
arr_hstacked = np.hstack((a, b))
print(arr_hstacked)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [17]:
# Input — do not modify
a = np.array([1, 2, 3])

In [18]:
output = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(output)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [19]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [20]:
common_items = np.intersect1d(a, b)
print(common_items)

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [21]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [22]:
removed_items = np.setdiff1d(a, b)
print(removed_items)

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [23]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [24]:
matching_positions = np.where(a == b)
print(matching_positions)

(array([1, 3, 5, 7]),)


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [25]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [26]:
filtered_items = a[(a >= 5) & (a <= 10)]
print(filtered_items)

[ 6  9 10]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [27]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [28]:
pair_max = np.vectorize(maxx)
result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [29]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [30]:
arr_swapped_cols = arr[:, [0, 2, 1]]
print(arr_swapped_cols)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [31]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [32]:
arr_swapped_rows = arr[[0, 2, 1], :]
print(arr_swapped_rows)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [33]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [34]:
arr_reversed_rows = arr[::-1]
print(arr_reversed_rows)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [35]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [36]:
arr_reversed_cols = arr[:, ::-1]
print(arr_reversed_cols)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [37]:
random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)

[[8.56299768 7.24205574 6.6876189 ]
 [5.25541848 8.39872632 8.17741063]
 [5.38968683 6.67264244 6.80678779]
 [9.95718226 7.31525411 6.47171407]
 [6.04079322 8.08215237 8.25461674]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [38]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [39]:
np.set_printoptions(precision=3)
print(rand_arr)

[[0.008 0.476 0.222]
 [0.127 0.982 0.515]
 [0.156 0.384 0.364]
 [0.712 0.605 0.122]
 [0.455 0.213 0.196]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [40]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [41]:
np.set_printoptions(suppress=True)
print(rand_arr)

[[0.001 0.    0.   ]
 [0.001 0.    0.   ]
 [0.001 0.001 0.   ]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [42]:
# Input — do not modify
a = np.arange(15)

In [43]:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [44]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [45]:
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [46]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_data = np.genfromtxt(url, delimiter=',', dtype=object)
print(iris_data[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [47]:
species = iris_data[:, 4]
print(species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [48]:
iris_2d = iris_data[:, :4].astype(float)
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [49]:
sepal_length = iris_2d[:, 0]
mean_sepal = np.mean(sepal_length)
median_sepal = np.median(sepal_length)
std_sepal = np.std(sepal_length)
print(f"Mean: {mean_sepal:.2f}, Median: {median_sepal:.2f}, Standard Deviation: {std_sepal:.2f}")

Mean: 5.84, Median: 5.80, Standard Deviation: 0.83


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [50]:
sepal_length = iris_2d[:, 0]
normalized_sepal_length = (sepal_length - sepal_length.min()) / (sepal_length.max() - sepal_length.min())
print(normalized_sepal_length[:5])

[0.222 0.167 0.111 0.083 0.194]


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [51]:
sepal_length = iris_2d[:, 0]
softmax_score = np.exp(sepal_length) / np.sum(np.exp(sepal_length))
print(softmax_score[:5])

[0.002 0.002 0.001 0.001 0.002]


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [52]:
sepal_length = iris_2d[:, 0]
percentiles = np.percentile(sepal_length, q=[5, 95])
print(f"5th Percentile: {percentiles[0]:.2f}, 95th Percentile: {percentiles[1]:.2f}")

5th Percentile: 4.60, 95th Percentile: 7.25


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [53]:
iris_2d_nan = iris_2d.copy()
r = np.random.randint(0, iris_2d_nan.shape[0], 20)
c = np.random.randint(0, iris_2d_nan.shape[1], 20)
iris_2d_nan[r, c] = np.nan
print(iris_2d_nan[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  nan 1.4 0.2]]


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [54]:
sepal_length_nan = iris_2d_nan[:, 0]
num_missing = np.isnan(sepal_length_nan).sum()
positions = np.where(np.isnan(sepal_length_nan))
print(f"Number of missing values: {num_missing}")
print(f"Positions of missing values: {positions}")

Number of missing values: 2
Positions of missing values: (array([67, 93]),)


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [55]:
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_rows[:5])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [56]:
rows_without_nan = iris_2d_nan[~np.isnan(iris_2d_nan).any(axis=1)]
print(rows_without_nan[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.4 3.9 1.7 0.4]]


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [57]:
correlation = np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])
print(correlation)

[[1.    0.872]
 [0.872 1.   ]]


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [58]:
has_nan = np.isnan(iris_2d_nan).any()
print(f"Iris_2d has missing values: {has_nan}")

Iris_2d has missing values: True


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [59]:
iris_2d_no_nan = np.nan_to_num(iris_2d_nan)
print(iris_2d_no_nan[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  0.  1.4 0.2]]


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [60]:
unique_species, counts = np.unique(iris_data[:, 4], return_counts=True)
print(f"Unique species: {unique_species}")
print(f"Counts: {counts}")

Unique species: [b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']
Counts: [50 50 50]


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [61]:
petal_length = iris_2d[:, 2]
petal_categories = np.where(petal_length < 3, 'small',
                         np.where((petal_length >= 3) & (petal_length < 5), 'medium', 'large'))
print(petal_categories[:5])

['small' 'small' 'small' 'small' 'small']


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [62]:
sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]
volume = (np.pi * petal_length * sepal_length**2) / 3
iris_with_volume = np.c_[iris_2d, volume]
print(iris_with_volume[:5])

[[ 5.1    3.5    1.4    0.2   38.133]
 [ 4.9    3.     1.4    0.2   35.2  ]
 [ 4.7    3.2    1.3    0.2   30.072]
 [ 4.6    3.1    1.5    0.2   33.238]
 [ 5.     3.6    1.4    0.2   36.652]]


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [63]:
species = iris_data[:, 4]
unique_species, counts = np.unique(species, return_counts=True)
total_samples = len(species)

setosa_prob = 2 / 4
versicolor_prob = 1 / 4
virginica_prob = 1 / 4

sampled_species = np.random.choice(unique_species, size=total_samples, p=[setosa_prob, versicolor_prob, virginica_prob])
print(sampled_species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-virginica']


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [64]:
setosa_petal_lengths = iris_2d[iris_data[:, 4] == b'Iris-setosa', 2]
sorted_petal_lengths = np.sort(setosa_petal_lengths)
second_longest_petal = sorted_petal_lengths[-2]
print(f"Second longest petal length for Setosa: {second_longest_petal:.2f}")

Second longest petal length for Setosa: 1.90


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [65]:
sorted_iris_2d = iris_2d[iris_2d[:, 0].argsort()]
print(sorted_iris_2d[:5])

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]]


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [66]:
petal_length = iris_2d[:, 2]
counts = np.bincount(petal_length.astype(int))
most_frequent_value = np.argmax(counts)
print(f"Most frequent petal length value: {most_frequent_value}")

Most frequent petal length value: 1


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [67]:
petal_width = iris_2d[:, 3]
position = np.where(petal_width > 1.0)[0][0]
print(f"First occurrence of a value greater than 1.0 in petal width is at position: {position}")

First occurrence of a value greater than 1.0 in petal width is at position: 50


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [68]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [69]:
clipped_a = np.clip(a, a_min=10, a_max=30)
print(clipped_a)

[27.627 14.64  21.801 30.    10.    10.    30.    30.    10.    29.18
 30.    11.251 10.081 10.    11.765 30.    30.    10.    30.    14.43 ]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [70]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [71]:
top_5_positions = a.argsort()[-5:][::-1]
print(f"Positions of the top 5 maximum values: {top_5_positions}")

Positions of the top 5 maximum values: [15 10  3  7 18]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [72]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [73]:
unique_counts_row_wise = np.apply_along_axis(lambda x: len(np.unique(x)), axis=1, arr=arr)
print(unique_counts_row_wise)

[7 7 5 7 7 8]


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [74]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [75]:
flat_array = np.concatenate(arr_2d)
print(flat_array)

[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.